FROM trucknet/android-react-native-ci-alpine:android-28
LABEL maintainer="Hugo Gresse <hugo.gresse@gmail.com>"

# Install Python
RUN apk add --no-cache python3
RUN ln -s /usr/bin/python3 /usr/bin/python
