FROM trucknet/android-react-native-ci-alpine:android-28
LABEL maintainer="Hugo Gresse <hugo.gresse@gmail.com>"

# Install Python
RUN apk add --no-cache python2 \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev

